path_2_raw_data_input: 'data/sourcedata/heart_cleveland_upload.csv'
path_2_ready_model: "model/logreg/finalized_model.sav"

model_name: 'LogisticRegression'
test_size: 0.2
random_state: 42
max_iter: 10000
grid: True